name: Slack
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: chat-with-sentiment
    required: true
  - name: webhook_url
    inputType: Secret
    description: The webhook url to send notifications to
    defaultValue: slackWebhook
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
